**Anomaly Detection** is the identification of rare items, events or suspicious observations, since they are far from common operations over the data. Tipically, anomaly detection may regard bank frauds, a structural defect, medical issues or text errors. Apply here Deep Learning by exploiting some anomaly detection datasets. The first is, a credit card frauds dataset: https://www.kaggle.com/mlg-ulb/creditcardfraud. Make and Exploratory Analysis and a Supervised Anomaly Detection with Deep Neural Netoworks. If needed, make use of other public datasets. Make all necessary plots and panels. 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#import csv
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/creditcard.csv")

In [ ]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [ ]:
x_Train = df.drop("Class",axis=1)
labels = df.loc[:,['Class']]

In [ ]:
labels.head()

Class
0      0
1      0
2      0
3      0
4      0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_Train, labels, test_size=0.3, random_state=42)

In [ ]:
#from sklearn.ensemble import RandomForestClassifier
#model = RandomForestClassifier()

In [ ]:
import tensorflow as tf
train_X = tf.convert_to_tensor(df.drop("Class",axis=1))
labels = df.loc[:,['Class']]

In [ ]:
train_X[:10]

<tf.Tensor: shape=(10, 30), dtype=float64, numpy=
array([[ 0.00000000e+00, -1.35980713e+00, -7.27811733e-02,
         2.53634674e+00,  1.37815522e+00, -3.38320770e-01,
         4.62387778e-01,  2.39598554e-01,  9.86979013e-02,
         3.63786970e-01,  9.07941720e-02, -5.51599533e-01,
        -6.17800856e-01, -9.91389847e-01, -3.11169354e-01,
         1.46817697e+00, -4.70400525e-01,  2.07971242e-01,
         2.57905802e-02,  4.03992960e-01,  2.51412098e-01,
        -1.83067779e-02,  2.77837576e-01, -1.10473910e-01,
         6.69280749e-02,  1.28539358e-01, -1.89114844e-01,
         1.33558377e-01, -2.10530535e-02,  1.49620000e+02],
       [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01,
         1.66480113e-01,  4.48154078e-01,  6.00176493e-02,
        -8.23608088e-02, -7.88029833e-02,  8.51016549e-02,
        -2.55425128e-01, -1.66974414e-01,  1.61272666e+00,
         1.06523531e+00,  4.89095016e-01, -1.43772296e-01,
         6.35558093e-01,  4.63917041e-01, -1.14804663e-01,
     

In [ ]:
#model.fit(train_X,labels)

RuntimeError: ignored

In [ ]:
train_X.shape[1]

30

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_Train, labels, test_size=0.3, random_state=42)

In [ ]:
from tensorflow import keras
from keras import Sequential,layers,optimizers,metrics,losses
from keras.layers import Dense,Conv1D,LSTM,MaxPooling1D
import numpy as np
model = Sequential()
model.add(Conv1D(filters=256, kernel_size=5, padding='same', activation='relu', input_shape=(train_X.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(64))
model.add(Dense(units=1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']) 

h =  model.fit(x=X_train, y=y_train, batch_size=64, epochs=5, validation_split=0.1)

Epoch 1/5
2804/2804 [==============================] - 18s 6ms/step - loss: 0.0077 - accuracy: 0.9985 - val_loss: 0.0044 - val_accuracy: 0.9991
Epoch 2/5
2804/2804 [==============================] - 15s 5ms/step - loss: 0.0043 - accuracy: 0.9993 - val_loss: 0.0028 - val_accuracy: 0.9995
Epoch 3/5
2804/2804 [==============================] - 14s 5ms/step - loss: 0.0040 - accuracy: 0.9993 - val_loss: 0.0028 - val_accuracy: 0.9995
Epoch 4/5
2804/2804 [==============================] - 16s 6ms/step - loss: 0.0039 - accuracy: 0.9993 - val_loss: 0.0026 - val_accuracy: 0.9995
Epoch 5/5
2804/2804 [==============================] - 17s 6ms/step - loss: 0.0037 - accuracy: 0.9993 - val_loss: 0.0026 - val_accuracy: 0.9996


In [ ]:
preds = model.predict(X_test)

[[8.6312264e-01]
 [3.1914457e-04]
 [1.8265445e-04]
 ...
 [2.9634224e-04]
 [2.6567903e-04]
 [1.4317152e-04]]


In [ ]:
print(np.round(preds))

[[1.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [ ]:
print(y_test)

        Class
43428       1
49906       0
29474       0
276481      0
278846      0
...       ...
180795      0
259979      0
21885       0
217812      0
86348       0

[85443 rows x 1 columns]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, np.round(preds))

0.9994148145547324